name: 'publish metadata and artifacts with hc-releases'
description: 'Use hc-releases to create metadata and upload files.'
inputs:
  product-name:
    description: 'Product name'
    required: true
  version:
    description: 'Product version'
    required: true
  hc-releases-host:
    description: 'hc releases host'
    required: true
  hc-releases-key:
    description: 'hc releases api key'
    required: true
  metadata-file:
    description: 'Release metadatafile. This file should contain any static metadata.'
    required: false
    default: '.release/release-metadata.hcl'
  changelog-url:
    description: 'changelog URL to add to the release metadata'
    required: false
    default: ""

runs:
  using: "composite"
  steps:
      - name: Set required repo name env var
        shell: bash
        run: echo "REPO_NAME=$(echo ${{ github.repository }} | cut -f2 -d "/")" >> $GITHUB_ENV
      - name: Set version
        shell: bash
        run: |
          VERSION="${{ inputs.version }}"
          echo "VERSION=$(echo "${VERSION//v}")" >> $GITHUB_ENV
      - name: Create Release metadata
        shell: bash
        env:
          HC_RELEASES_HOST: ${{ inputs.hc-releases-host }}
          HC_RELEASES_KEY: ${{ inputs.hc-releases-key }}
          VERSION: ${{ env.VERSION }}
        run: |
          hc-releases metadata create -product "${{ inputs.product-name }}" \
          -add /version='"${{ env.VERSION }}"' \
          -add /url_changelog='"${{ inputs.changelog-url }}"' \
          -input "${{ inputs.metadata-file }}"