name: 'Publish metadata and artifacts with hc-releases'
description: 'Use hc-releases to create metadata and upload files.'
inputs:
  product-name:
    description: 'Product name'
    required: true
  version:
    description: 'Product version'
    required: true
  hc-releases-host:
    description: 'hc releases host'
    required: true
  hc-releases-key:
    description: 'hc releases api key'
    required: true
  metadata-file:
    description: 'Release metadatafile. This file should contain any static metadata.'
    required: false
    default: '.release/release-metadata.hcl'
  changelog:
    description: 'Add changelog URL to the release metadata'
    required: false
    default: 'true'
runs:
  using: "composite"
  steps:
      - name: Create Release Metadata
        shell: bash
        env:
          HC_RELEASES_HOST: ${{ inputs.hc-releases-host }}
          HC_RELEASES_KEY: ${{ inputs.hc-releases-key }}
          VERSION: ${{ inputs.version }}
          CHANGELOG: ${{ inputs.changelog }}
          METADATA_FILE: ${{ inputs.metadata-file }}
          PRODUCT_NAME: ${{ inputs.product-name }}
          REPO: ${{ github.repository }} 
        run: |
          ${{ github.action_path }}/scripts/create-metadata.sh
